export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENITHUSIASM';
export type INCREMENT_ENTHUSIASM =  typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = '';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;